command_timeout = 2000

[java]
detect_folders = ["java", "bazel-zoolander"]
style = "bold green"
format = "[$symbol$version]($style) "

[python]
format = "[$symbol$version]($style) "
style = "bold green"
disabled = true

[ruby]
format = "[$symbol$version]($style) "
style = "bold green"

[nodejs]
format = ""

[directory]
truncation_length = 100
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ğŸŒ± "
format = '[$symbol$branch]($style) '

[git_status]
untracked = ""
stashed = ""
conflicted = "ğŸ³"